// client/src/components/Aside.tsx
import React from 'react'
import { Avatar } from 'antd'
import { Link } from "react-router-dom";
import {
    HomeFilled,
    DashboardFilled,
    MessageFilled,
    SettingFilled
} from '@ant-design/icons';
import { Menu } from 'antd';


interface PropsType {
    user?: any
}

const Aside = (props: PropsType) => {
    const { user } = props;

    return (
        <div className="aside">
            <div className="avatar">
                <div className="avatarBg">
                    <Avatar src={user.avatar} size="large" shape="square" />
                </div>
                <div className="user">
                    {user.username}
                </div>
            </div>
            <div className="config">
                <Menu
                    defaultSelectedKeys={['1']}
                    defaultOpenKeys={['sub1']}
                    mode="inline"
                    inlineCollapsed={false}
                >
                    <Menu.Item key="1" icon={<HomeFilled />}>
                        <Link to='/'>
                            Home
                        </Link>
                    </Menu.Item>
                    <Menu.Item key="2" icon={<DashboardFilled />}>
                        <Link to='/dashboard'>
                            Dashboard
                        </Link>
                    </Menu.Item>
                    <Menu.Item key="3" icon={<MessageFilled />}>
                        <Link to='/setting'>
                            Message
                       </Link>
                    </Menu.Item>
                    <Menu.Item key="4" icon={<SettingFilled />}>
                        <Link to='/setting'>
                            Setting
                       </Link>
                    </Menu.Item>
                </Menu>
            </div>
        </div>
    );
};

export default Aside;

// client/components/Layouts/Aside.vue
<template>
    <div class="aside">
        <div class="avatar">
            <div class="avatarBg">
                <a-avatar :src="user.avatar" size="large" shape="square" />
            </div>
            <div class="user">
                {{ user.username }}
            </div>
        </div>
        <div class="config">
            <a-menu v-model="openKeys" mode="inline" :inlineCollapsed="false">
                <a-menu-item v-for="item in menuList" :key="item.id" :title="item.name">
                    <a-icon :type="item.icon" theme="filled" />
                    <n-link :to="item.link" no-prefetch>{{ item.name }}</n-link>
                </a-menu-item>
            </a-menu>
        </div>
    </div>
</template>
<script>
export default {
    data() {
        return {
            rootSubmenuKeys: ['1', '2', '3', '4'],
            openKeys: ['1'],
            user: {},
            menuList: [
                {
                    icon: 'home',
                    name: 'Home',
                    link: '/',
                    id: '1',
                },
                {
                    icon: 'dashboard',
                    name: 'Dashboard',
                    link: '/dashboard',
                    id: '2',
                },
                {
                    icon: 'message',
                    name: 'Message',
                    link: '/message',
                    id: '3',
                },
                {
                    icon: 'setting',
                    name: 'Setting',
                    link: '/setting',
                    id: '4',
                },
            ],
        };
    },
    props: {
        getUser: Object,
        setMemuItem: Function,
    },
    watch: {
        getUser: {
            deep: true,
            handler: function (newData, oldData) {
                this.user = newData;
            },
        },
        openKeys: function (newValue, oldValu) {
            const memuTitle = this.menuList.filter(item => item.id == newValue[0]);
            this.$emit('setMemuItem', memuTitle[0]);
        },
    },
};
</script>
